### ISSUE TITLE
Issues with OS Packager design

### ISSUE THREAD

**Issue by kravets-levko** [smth/os-mockups#1]
1. Issue with input group addons size (probably, some dimensions were changed not through bootstrap's config and therefore not matching other components):
![image](https://cloud.githubusercontent.com/assets/12139186/22420502/557207c6-e6eb-11e6-9d0e-dcc9bd9eb116.png)
```html
<div class="col-xs-12">
    <div class="input-group">
      <span class="input-group-btn">
        <label class="btn btn-default">Upload a file</label>
      </span>
      <input id="step1-input-file" type="text" class="form-control">     
    </div>
  </div>
```

2. Issue with steps:
![image](https://cloud.githubusercontent.com/assets/12139186/22420567/afbd5dca-e6eb-11e6-94c4-75bf70e663de.png)
- lines are not properly positioned (I tried to figure it out by myself; probably it's caused by some 3rd-party css used in Packager)
- invalid highlight when choosing previous step (see screenshot).
- also I'm not sure that items should be underlined on hover, but it's the least evil.
My idea is to change markup: currently lines are placed after corresponding circle, and for the last circle line is hidden; try to change it so lines will be placed before the circle, and hide the first one. Also you can add as much state classes as you wish and remove that weird `~` selector.

3. Describe data cards:
![image](https://cloud.githubusercontent.com/assets/12139186/22420703/51f42b46-e6ec-11e6-8347-69e9a7e3edf0.png)
First of all, try to use this in the [http://next.openspending.org/packager/provide-data](Packager) (example valid CSV file is here: https://raw.githubusercontent.com/kravets-levko/data/master/test.csv).
- card can have more than three fields; actually, there may be any count of fields; `title`, `description` and `type` are just required ones.
- there may be also dropdown fields (`<select>`) - not present in current mockups.
- take a look at the bottom of the card: there is a popup (you will see how it looks like in the *live* Packager) - it's not possible to show it with the current markup (there is `overflow: hidden` somewhere). I also tried to workaround it, but seems that it's not so simple.

P.S. BTW - can you explain what that switch button is intended for?

**Comment by DianaMPG** [comment]
@smth this issue relates to  
https://github.com/openspending/openspending/issues/1130 and https://github.com/openspending/openspending/issues/1129

**Comment by smth** [comment]
1. I used different markup for the upload buttons http://p.smth.uk/os-mockup-packager/packager/provide-data/ Is this not an option?

2. I'm not seeing these issues here http://p.smth.uk/os-mockup-packager/packager/describe-data/ but I could add a background colour to the circles to hide any overlap. Sounds like we have established that the user will be able to go backwards in the steps, so we need additional styles. In particular one for when a step is complete, but you have navigated to an earlier one. Is this what you are asking for here @kravets-levko ? What is your thinking for having the line before the circle, rather than after (I can't remember why I did it the way I did)?

3. I think those cards are completely changing. These issues should probably be discussed as part of [that](https://github.com/openspending/openspending/issues/1131). If, as I believe, the additional fields are `type` specific, then they can be nested under the type in the [new concept](http://p.smth.uk/os-mockup-packager/packager/map-data/). Switches are not used in the new version, but a brief explanation of what they were intended for can be found [here](https://github.com/openspending/openspending/issues/1130#issuecomment-266381760).

**Comment by kravets-levko** [comment]
1. Yes (remember that I created this issue when that mockup didn't exist yet)

2. Do anything you wish, just know that user can go to any already passed step - he can go back, change something and then return to previous one. It's already implemented.

3. Same as for 1

**Comment by smth** [comment]
Ah yes, sorry.

Looking at the implemented version of the step numbers, I think it's all actually working fine. I'll close this issue because there seems to be nothing for me to do here.
